FROM mongo:latest
# Will be set through Environment Files
# COPY KeyFrameEdit.json /tmp

# CMD bash mongoimport --uri mongodb://192.168.20.156:27017/Video --collection KeyFrameEdit --type json --file KeyFrameEdit.json --jsonArray